CREATE DATABASE Project;

USE Project;

-- Validate Imported Data --

select * from Product;

select * from Location;

select * from fact;

-- 1. Display the number of states present in the LocationTable. --
select count( distinct state) as No_of_states from Location;

-- 2. How many products are of Regular type? --
select count(*) as Product_count from Product
where Product_Type = 'Regular';

-- 3. How much spending has been done on marketing of Product ID 1? --
select sum(Marketing) as total from fact
where ProductId = 1;

-- 4. What is the minimum sales of a product? --
select min(sales) as min_sales from fact;

-- 5. Display the maximum Cost of Goods Sold (COGS). --
select max(COGS) as max_cogs from fact;

-- 6. Display the details of the product where Product Type is Coffee. --
select * from Product where Product_Type = 'Coffee';

-- 7. Display the details where Total Expenses are greater than 40. --
select * from fact where Total_Expenses > 40;

-- 8. What is the average sales in Area Code 719? --
select avg(sales) as avg_sales from fact where Area_Code =719; 

-- 9. Find out the total profit generated by Colorado state. --
select sum(Profit) as total_profit from Fact F
Join Location L
On F.Area_Code = L.Area_Code
where L.State = 'Colorado';

-- 10. Display the average inventory for each Product ID. --
select ProductID, avg(Inventory) as Avg_Inventory from Fact
Group by ProductId;

-- 11. Display state in sequential order. --
select distinct State from Location 
Order by State;

-- 12. Display the average budget of the product where the average budget margin should be greater than 100. --
select ProductId, avg(Budget_Margin) as avg_Budget from fact
group by ProductId
having avg(Budget_Margin) > 100;

-- 13. What is the total sales done on date '2010-01-01'? --
select sum(Sales) as total_sales from fact
where Date = '2010-01-01';

-- 14. Display the average total expense of each Product ID on an individual date. --
select Date, ProductID, avg(Total_Expenses) AS Avg_expense FROM Fact
GROUP BY Date, ProductID;

-- 15. Display Date, ProductID, Product_Type, Product, Sales, Profit, State, AreaCode. --
SELECT F.Date, F.ProductID, P.Product_Type, P.Product, F.Sales, F.Profit, L.State, F.Area_Code
FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
JOIN Location L ON F.Area_Code = L.Area_Code;

-- 16. Display the rank without any gap to show sales-wise rank. --
SELECT Sales,
DENSE_RANK() OVER(ORDER BY Sales DESC) AS SalesRank
FROM Fact;

-- 17. Find the state-wise profit and sales. --
SELECT L.State, SUM(F.Profit) AS TotalProfit, SUM(F.Sales) AS TotalSales FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State;

-- 18. Find the state-wise profit and sales along with the product name.
SELECT L.State, P.Product, SUM(F.Profit) AS Profit, SUM(F.Sales) AS Sales FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State,P.Product;

-- 19. If there is an increase in sales of 5%, calculate the increased sales. --
SELECT Sales, Sales*1.05 AS IncreasedSales FROM Fact;

-- 20. Find the maximum profit along with Product ID and Product Type. --
SELECT TOP 1 F.ProductID, P.Product_Type, F.Profit FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
ORDER BY F.Profit DESC;

-- 21. Create a stored procedure to fetch products by Product Type. --

CREATE OR ALTER PROCEDURE dbo.Get_Product_By_Type
    @ProductType VARCHAR(50)
AS
BEGIN
    SELECT *
    FROM Product
    WHERE Product_Type = @ProductType;
END;

-- Execute the stored procedure
EXEC dbo.Get_Product_By_Type 'Coffee';

-- 22. If Total Expenses < 60 then Profit else Loss. --
select *,
case
when Total_Expenses < 60 then 'Profit'
else 'Loss'
END AS Status
from fact;

-- 23. Calculate hierarchical sales totals by Date and ProductID using ROLLUP. --
SELECT Date, ProductID, SUM(Sales) AS TotalSales FROM Fact
GROUP BY ROLLUP(Date,ProductID);

-- 24. Apply UNION and INTERSECT on AreaCode. --

-- UNION
SELECT Area_Code FROM Fact
UNION
SELECT Area_Code FROM Location;

--INTERSECT
SELECT Area_Code FROM Fact
INTERSECT
SELECT Area_Code FROM Location;

-- 25. Create a user-defined function to fetch products by Product Type. --

CREATE FUNCTION dbo.GetProductType
(
    @ProductType VARCHAR(50)
)
RETURNS TABLE
AS
RETURN
(
    SELECT *
    FROM Product
    WHERE Product_Type = @ProductType
);
GO

-- Execute the function
SELECT *
FROM dbo.GetProductType('Coffee');

-- 26. Demonstrate UPDATE operation using a transaction. --
BEGIN TRANSACTION;
UPDATE Product SET Product_Type = 'Tea' WHERE ProductID = 1;
ROLLBACK;

-- 27. Display Date, ProductID and Sales where Total Expenses are between 100 and 200. --
SELECT Date, ProductID, Sales FROM Fact
WHERE Total_Expenses BETWEEN 100 AND 200;

-- 28. Demonstrate DELETE operation safely using a transaction. --
BEGIN TRANSACTION;
DELETE FROM Product WHERE Product_Type = 'Regular';
ROLLBACK;

-- 29. Display the ASCII value of the fifth character from the Product column. --
SELECT Product, ASCII(SUBSTRING(Product,5,1)) AS ASCII_Value FROM Product;

-- 30. Display the Top 10 Highest Selling Products. --
select top 10 P.Product, sum(F.Sales) as Total_sales from fact F
Join Product P ON F.ProductId = P.ProductId
Group by P.Product
Order by Total_sales Desc;

-- 31. Display the Top 10 Most Profitable Products. --
SELECT TOP 10 P.Product, SUM(F.Profit) AS TotalProfit FROM Fact F
JOIN Product P ON F.ProductID = P.ProductID
GROUP BY P.Product
ORDER BY TotalProfit DESC;

-- 32. Calculate the Profit Margin (%) for each Product --
SELECT ProductID, Sales, Profit, ROUND((Profit * 100.0) / Sales,2) AS ProfitMargin FROM Fact
WHERE Sales > 0;

-- 33. Display the Monthly Sales Trend. --
SELECT YEAR(Date) AS Year, MONTH(Date) AS Month, SUM(Sales) AS Total_Sales FROM Fact
GROUP BY YEAR(Date), MONTH(Date)
ORDER BY Year, Month;

-- 34. Find the Top 5 Best Performing States based on Sales. --
SELECT TOP 5 L.State, SUM(F.Sales) AS Total_Sales FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State
ORDER BY Total_Sales DESC;

-- 35. Find the Bottom 5 States based on Sales --
SELECT TOP 5 L.State, SUM(F.Sales) AS Total_Sales FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State
ORDER BY Total_Sales;

-- 36. Display the Average Inventory of all Products in Descending Order. --
SELECT ProductID, AVG(Inventory) AS Avg_Inventory FROM Fact
GROUP BY ProductID
ORDER BY Avg_Inventory DESC;

-- 37. Calculate the Total Marketing Cost and Total Profit for each Product. --
SELECT ProductID, SUM(Marketing) AS Total_Marketing, SUM(Profit) AS Total_Profit FROM Fact
GROUP BY ProductID;

-- 38. Display the Running Total of Sales. --
SELECT Date, Sales, SUM(Sales) OVER(ORDER BY Date) AS Running_Total_Sales FROM Fact;

-- 39. Rank Products based on Total Sales. --
SELECT ProductID, SUM(Sales) AS TotalSales,
DENSE_RANK() OVER(ORDER BY SUM(Sales) DESC) AS SalesRank FROM Fact
GROUP BY ProductID;

-- 40. Find the Product with the Highest Profit. --
SELECT TOP 1 F.ProductID, P.Product, SUM(F.Profit) AS Total_Profit FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
GROUP BY F.ProductID,P.Product ORDER BY Total_Profit DESC;

-- 41. Display the Total Sales, Profit and COGS for each Product Type.
SELECT P.Product_Type, SUM(F.Sales) AS Total_Sales, SUM(F.Profit) AS Total_Profit, SUM(F.COGS) AS Total_COGS FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
GROUP BY P.Product_Type;

-- 42. Display the Number of Products available in each Product Type. --
SELECT Product_Type, COUNT(*) AS Number_Of_Products FROM Product
GROUP BY Product_Type;

-- 43. Find Products whose Sales are greater than the Average Sales. --
SELECT * FROM Fact WHERE Sales > (SELECT AVG(Sales)FROM Fact);

-- 44. Display the Highest Sales recorded in each State --
SELECT L.State, MAX(F.Sales) AS Highest_Sales FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State;

-- 45. Find the Total Sales generated by each Product. --
SELECT P.Product, SUM(F.Sales) AS Total_Sales FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
GROUP BY P.Product;

-- 46. Display the Top 3 Products based on Inventory.
SELECT TOP 3 ProductID, AVG(Inventory) AS Avg_Inventory FROM Fact
GROUP BY ProductID
ORDER BY Avg_Inventory DESC;

-- 47. Find the Percentage Contribution of each Product to Total Sales. --
SELECT ProductID, SUM(Sales) AS ProductSales,
ROUND(SUM(Sales)*100.0/(SELECT SUM(Sales) FROM Fact),2) AS Sales_Percentage FROM Fact
GROUP BY ProductID;

-- 48. Display all Products that have never generated a Profit. --
SELECT DISTINCT ProductID FROM Fact WHERE Profit<=0;

-- 49. Find the State that has the Highest Average Profit. --
SELECT TOP 1 L.State, AVG(F.Profit) AS Average_Profit FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State ORDER BY Average_Profit DESC;

-- 50. Display the Total Sales, Profit, Marketing Cost and Inventory for every Product. --
SELECT P.Product, SUM(F.Sales) AS Total_Sales, SUM(F.Profit) AS Total_Profit, SUM(F.Marketing) AS Marketing_Cost, AVG(F.Inventory) AS Average_Inventory
FROM Fact F JOIN Product P ON F.ProductID=P.ProductID GROUP BY P.Product;

-- 51. Find the Second Highest Sales. --
SELECT MAX(Sales) AS Second_Highest_Sales FROM Fact
WHERE Sales <(SELECT MAX(Sales)FROM Fact);

-- 52. Dispplay the top 5 dates with the highest sales. --
SELECT TOP 5 Date, SUM(Sales) AS Total_Sales FROM Fact
GROUP BY Date ORDER BY Total_Sales DESC;

-- 53. Dispplay the sales category using CASE statement. --
SELECT ProductID, Sales,
 CASE
   WHEN Sales>=500 THEN 'High'
   WHEN Sales>=200 THEN 'Medium'
   ELSE 'Low'
  END AS SalesCategory
FROM Fact;

-- 54. Find the Products having Profit greater than 100. --
SELECT DISTINCT P.Product FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
WHERE F.Profit>100;

-- 55. Display the Total Sales and Profit Month-wise. --
SELECT YEAR(Date) AS Year, MONTH(Date) AS Month, SUM(Sales) AS Total_Sales, SUM(Profit) AS Total_Profit FROM Fact
GROUP BY YEAR(Date),MONTH(Date) ORDER BY Year,Month;

-- View1: Sales Report

CREATE VIEW vw_SalesReport
AS
SELECT
    F.Date,
    P.Product,
    P.Product_Type,
    L.State,
    F.Sales,
    F.Profit,
    F.COGS,
    F.Marketing
FROM Fact F
JOIN Product P ON F.ProductID=P.ProductID
JOIN Location L ON F.Area_Code=L.Area_Code;

SELECT * FROM vw_SalesReport;

-- View2: State Performance

CREATE VIEW vw_StatePerformance
AS
SELECT
    L.State,
    SUM(F.Sales) AS TotalSales,
    SUM(F.Profit) AS TotalProfit
FROM Fact F
JOIN Location L ON F.Area_Code=L.Area_Code
GROUP BY L.State;

SELECT * FROM vw_StatePerformance;

-- View3: Product Performance

CREATE VIEW vw_ProductPerformance
AS
SELECT
    P.Product,
    P.Product_Type,
    SUM(F.Sales) AS TotalSales,
    SUM(F.Profit) AS TotalProfit,
    SUM(F.Marketing) AS TotalMarketing,
    AVG(F.Inventory) AS AverageInventory
FROM Fact F
JOIN Product P
    ON F.ProductID = P.ProductID
GROUP BY
    P.Product,
    P.Product_Type;

SELECT * FROM vw_ProductPerformance;

-- INDEXES

CREATE INDEX IX_ProductID ON Fact(ProductID);
CREATE INDEX IX_Area_Code ON Fact(Area_Code);
CREATE INDEX IX_Date ON Fact(Date);
EXEC sp_helpindex 'Fact';

-- TRANSACTION DEMONSTRATION

BEGIN TRANSACTION;

UPDATE Product
SET Product_Type = 'Tea'
WHERE ProductID = 1;

-- Verify the change if required
SELECT *
FROM Product
WHERE ProductID = 1;

ROLLBACK;

-- ERROR HANDLING

BEGIN TRY
SELECT * FROM Product;
END TRY

BEGIN CATCH
PRINT ERROR_MESSAGE();
END CATCH;
